FROM mcr.microsoft.com/devcontainers/go:2-1.26-trixie

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends maven \
    && apt-get -y install --no-install-recommends git \
    && apt-get -y install visualvm \
    && apt-get -y install build-essential \
    && apt-get -y install telnet \
    && apt-get -y install htop \
    && apt-get -y install tree \
    && apt-get -y install unzip \
    && apt-get -y install vim \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace